/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mav_nmpc_tracker_model_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

static const casadi_int casadi_s0[8] = {3, 2, 0, 2, 3, 0, 1, 2};
static const casadi_int casadi_s1[9] = {2, 3, 0, 1, 2, 3, 0, 0, 1};
static const casadi_int casadi_s2[10] = {3, 2, 0, 2, 5, 0, 1, 0, 1, 2};
static const casadi_int casadi_s3[9] = {3, 2, 0, 2, 4, 0, 1, 0, 1};
static const casadi_int casadi_s4[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s5[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s6[11] = {3, 2, 0, 3, 6, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s7[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s8[3] = {0, 0, 0};
static const casadi_int casadi_s9[12] = {3, 3, 0, 2, 4, 6, 0, 1, 0, 1, 0, 1};

/* mav_nmpc_tracker_model_expl_vde_forw:(i0[3],i1[3x3],i2[3x2],i3[2],i4[])->(o0[3],o1[3x3,6nz],o2[3x2,5nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, w5, *w6=w+9, *w7=w+18, *w8=w+21, *w9=w+24, w10, w11, w12, *w13=w+30, *w14=w+32, *w15=w+37, *w17=w+43, *w18=w+45, *w19=w+49;
  /* #0: @0 = 0.5 */
  w0 = 5.0000000000000000e-01;
  /* #1: @1 = input[3][0] */
  w1 = arg[3] ? arg[3][0] : 0;
  /* #2: @0 = (@0+@1) */
  w0 += w1;
  /* #3: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #4: @3 = cos(@2) */
  w3 = cos( w2 );
  /* #5: @4 = (@0*@3) */
  w4  = (w0*w3);
  /* #6: @5 = 0.5 */
  w5 = 5.0000000000000000e-01;
  /* #7: @4 = (@4-@5) */
  w4 -= w5;
  /* #8: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  /* #9: @4 = 0.5 */
  w4 = 5.0000000000000000e-01;
  /* #10: @4 = (@4+@1) */
  w4 += w1;
  /* #11: @1 = sin(@2) */
  w1 = sin( w2 );
  /* #12: @5 = (@4*@1) */
  w5  = (w4*w1);
  /* #13: output[0][1] = @5 */
  if (res[0]) res[0][1] = w5;
  /* #14: @5 = input[3][1] */
  w5 = arg[3] ? arg[3][1] : 0;
  /* #15: output[0][2] = @5 */
  if (res[0]) res[0][2] = w5;
  /* #16: @5 = sin(@2) */
  w5 = sin( w2 );
  /* #17: @6 = input[1][0] */
  casadi_copy(arg[1], 9, w6);
  /* #18: {@7, @8, @9} = horzsplit(@6) */
  casadi_copy(w6, 3, w7);
  casadi_copy(w6+3, 3, w8);
  casadi_copy(w6+6, 3, w9);
  /* #19: {NULL, NULL, @10} = vertsplit(@7) */
  w10 = w7[2];
  /* #20: @11 = (@5*@10) */
  w11  = (w5*w10);
  /* #21: @11 = (@0*@11) */
  w11  = (w0*w11);
  /* #22: @11 = (-@11) */
  w11 = (- w11 );
  /* #23: output[1][0] = @11 */
  if (res[1]) res[1][0] = w11;
  /* #24: @11 = cos(@2) */
  w11 = cos( w2 );
  /* #25: @10 = (@11*@10) */
  w10  = (w11*w10);
  /* #26: @10 = (@4*@10) */
  w10  = (w4*w10);
  /* #27: output[1][1] = @10 */
  if (res[1]) res[1][1] = w10;
  /* #28: {NULL, NULL, @10} = vertsplit(@8) */
  w10 = w8[2];
  /* #29: @12 = (@5*@10) */
  w12  = (w5*w10);
  /* #30: @12 = (@0*@12) */
  w12  = (w0*w12);
  /* #31: @12 = (-@12) */
  w12 = (- w12 );
  /* #32: output[1][2] = @12 */
  if (res[1]) res[1][2] = w12;
  /* #33: @10 = (@11*@10) */
  w10  = (w11*w10);
  /* #34: @10 = (@4*@10) */
  w10  = (w4*w10);
  /* #35: output[1][3] = @10 */
  if (res[1]) res[1][3] = w10;
  /* #36: {NULL, NULL, @10} = vertsplit(@9) */
  w10 = w9[2];
  /* #37: @5 = (@5*@10) */
  w5 *= w10;
  /* #38: @5 = (@0*@5) */
  w5  = (w0*w5);
  /* #39: @5 = (-@5) */
  w5 = (- w5 );
  /* #40: output[1][4] = @5 */
  if (res[1]) res[1][4] = w5;
  /* #41: @11 = (@11*@10) */
  w11 *= w10;
  /* #42: @11 = (@4*@11) */
  w11  = (w4*w11);
  /* #43: output[1][5] = @11 */
  if (res[1]) res[1][5] = w11;
  /* #44: @9 = zeros(2x3,3nz) */
  casadi_clear(w9, 3);
  /* #45: @13 = ones(2x1) */
  casadi_fill(w13, 2, 1.);
  /* #46: {@11, @10} = vertsplit(@13) */
  w11 = w13[0];
  w10 = w13[1];
  /* #47: @3 = (@3*@11) */
  w3 *= w11;
  /* #48: @1 = (@1*@11) */
  w1 *= w11;
  /* #49: @8 = vertcat(@3, @1, @10) */
  rr=w8;
  *rr++ = w3;
  *rr++ = w1;
  *rr++ = w10;
  /* #50: (@9[:3] = @8) */
  for (rr=w9+0, ss=w8; rr!=w9+3; rr+=1) *rr = *ss++;
  /* #51: @8 = @9' */
  casadi_trans(w9,casadi_s1, w8, casadi_s0, iw);
  /* #52: @14 = project(@8) */
  casadi_project(w8, casadi_s0, w14, casadi_s2, w);
  /* #53: @3 = sin(@2) */
  w3 = sin( w2 );
  /* #54: @15 = input[2][0] */
  casadi_copy(arg[2], 6, w15);
  /* #55: {@8, @9} = horzsplit(@15) */
  casadi_copy(w15, 3, w8);
  casadi_copy(w15+3, 3, w9);
  /* #56: {NULL, NULL, @1} = vertsplit(@8) */
  w1 = w8[2];
  /* #57: @10 = (@3*@1) */
  w10  = (w3*w1);
  /* #58: @10 = (@0*@10) */
  w10  = (w0*w10);
  /* #59: @10 = (-@10) */
  w10 = (- w10 );
  /* #60: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #61: @1 = (@2*@1) */
  w1  = (w2*w1);
  /* #62: @1 = (@4*@1) */
  w1  = (w4*w1);
  /* #63: @16 = 00 */
  /* #64: @13 = vertcat(@10, @1, @16) */
  rr=w13;
  *rr++ = w10;
  *rr++ = w1;
  /* #65: {NULL, NULL, @10} = vertsplit(@9) */
  w10 = w9[2];
  /* #66: @3 = (@3*@10) */
  w3 *= w10;
  /* #67: @0 = (@0*@3) */
  w0 *= w3;
  /* #68: @0 = (-@0) */
  w0 = (- w0 );
  /* #69: @2 = (@2*@10) */
  w2 *= w10;
  /* #70: @4 = (@4*@2) */
  w4 *= w2;
  /* #71: @16 = 00 */
  /* #72: @17 = vertcat(@0, @4, @16) */
  rr=w17;
  *rr++ = w0;
  *rr++ = w4;
  /* #73: @18 = horzcat(@13, @17) */
  rr=w18;
  for (i=0, cs=w13; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<2; ++i) *rr++ = *cs++;
  /* #74: @19 = project(@18) */
  casadi_project(w18, casadi_s3, w19, casadi_s2, w);
  /* #75: @14 = (@14+@19) */
  for (i=0, rr=w14, cs=w19; i<5; ++i) (*rr++) += (*cs++);
  /* #76: output[2][0] = @14 */
  casadi_copy(w14, 5, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void mav_nmpc_tracker_model_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mav_nmpc_tracker_model_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int mav_nmpc_tracker_model_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real mav_nmpc_tracker_model_expl_vde_forw_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mav_nmpc_tracker_model_expl_vde_forw_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mav_nmpc_tracker_model_expl_vde_forw_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mav_nmpc_tracker_model_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mav_nmpc_tracker_model_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s9;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mav_nmpc_tracker_model_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 3;
  if (sz_w) *sz_w = 54;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
